# Generated by Django 3.2.16 on 2022-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20221026_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
