# Generated by Django 3.2.16 on 2022-10-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_employee_is_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jr.', 'Junior'), ('reg.', 'Regular'), ('sr.', 'Senior')], max_length=4),
        ),
    ]
