# Generated by Django 3.2.16 on 2022-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_employee_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior'), ('Regular', 'Regular')], max_length=7, verbose_name='Seniority Level'),
        ),
    ]
